<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $users = [
            [
                'first_name' => 'User1',
                'last_name' => 'Latakia',
                'wallet_balance' => 0.0,
                'avatar' => null,
                'email' => 'user1.latakia@gmail.com',
                'email_verified' => true,
                'country_code' => '+963',
                'phone_number' => '944123456',
                'phone_verified' => true,
                'password_raw' => 'Latakia_123',
                'role' => 'employee',
                'id_verified' => 'none',
                'bank_details' => null,
                'status' => 'active',
                'otp' => null,
                'otp_expire_at' => null,
                'is_verified' => true,
            ],
            [
                'first_name' => 'User2',
                'last_name' => 'Latakia',
                'wallet_balance' => 0.0,
                'avatar' => null,
                'email' => 'user2.latakia@gmail.com',
                'email_verified' => true,
                'country_code' => '+963',
                'phone_number' => '944654321',
                'phone_verified' => true,
                'password_raw' => 'Latakia_456',
                'role' => 'employee',
                'id_verified' => 'none',
                'bank_details' => null,
                'status' => 'active',
                'otp' => null,
                'otp_expire_at' => null,
                'is_verified' => true,
            ],
            [
                'first_name' => 'User1',
                'last_name' => 'Damascus',
                'wallet_balance' => 0.0,
                'avatar' => null,
                'email' => 'user1.damascus@gmail.com',
                'email_verified' => true,
                'country_code' => '+963',
                'phone_number' => '933111222',
                'phone_verified' => true,
                'password_raw' => 'Damascus_123',
                'role' => 'employee',
                'id_verified' => 'none',
                'bank_details' => null,
                'status' => 'active',
                'otp' => null,
                'otp_expire_at' => null,
                'is_verified' => true,
            ],
            [
                'first_name' => 'User2',
                'last_name' => 'Damascus',
                'wallet_balance' => 0.0,
                'avatar' => null,
                'email' => 'user2.damascus@gmail.com',
                'email_verified' => true,
                'country_code' => '+963',
                'phone_number' => '933333444',
                'phone_verified' => true,
                'password_raw' => 'Damascus_456',
                'role' => 'employee',
                'id_verified' => 'none',
                'bank_details' => null,
                'status' => 'active',
                'otp' => null,
                'otp_expire_at' => null,
                'is_verified' => true,
            ],
            [
                'first_name' => 'User3',
                'last_name' => 'Damascus',
                'wallet_balance' => 0.0,
                'avatar' => null,
                'email' => 'user3.damascus@gmail.com',
                'email_verified' => true,
                'country_code' => '+963',
                'phone_number' => '933555666',
                'phone_verified' => true,
                'password_raw' => 'Damascus_789',
                'role' => 'employee',
                'id_verified' => 'none',
                'bank_details' => null,
                'status' => 'active',
                'otp' => null,
                'otp_expire_at' => null,
                'is_verified' => true,
            ],
            [
                'first_name' => 'User4',
                'last_name' => 'Damascus',
                'wallet_balance' => 0.0,
                'avatar' => null,
                'email' => 'user4.damascus@gmail.com',
                'email_verified' => true,
                'country_code' => '+963',
                'phone_number' => '933777888',
                'phone_verified' => true,
                'password_raw' => 'Damascus_101',
                'role' => 'employee',
                'id_verified' => 'none',
                'bank_details' => null,
                'status' => 'active',
                'otp' => null,
                'otp_expire_at' => null,
                'is_verified' => true,
            ],
            [
                'first_name' => 'User1',
                'last_name' => 'Idleb',
                'wallet_balance' => 0.0,
                'avatar' => null,
                'email' => 'user1.idleb@gmail.com',
                'email_verified' => true,
                'country_code' => '+963',
                'phone_number' => '955111222',
                'phone_verified' => true,
                'password_raw' => 'Idleb_999',
                'role' => 'admin',
                'id_verified' => 'approved',
                'bank_details' => 'Bank ABC, Account 987654321',
                'status' => 'active',
                'otp' => null,
                'otp_expire_at' => null,
                'is_verified' => true,
            ],
            [
                'first_name' => 'User3',
                'last_name' => 'Latakia',
                'wallet_balance' => 0.0,
                'avatar' => null,
                'email' => 'user3.latakia@gmail.com',
                'email_verified' => true,
                'country_code' => '+963',
                'phone_number' => '944987654',
                'phone_verified' => true,
                'password_raw' => 'Latakia_789',
                'role' => 'employee',
                'id_verified' => 'none',
                'bank_details' => null,
                'status' => 'active',
                'otp' => null,
                'otp_expire_at' => null,
                'is_verified' => true,
            ],
        ];

        foreach ($users as $user) {
            $userData = $user;
            $userData['password'] = Hash::make($user['password_raw']);
            unset($userData['password_raw']);
            User::create($userData);
        }
    }
}
